# Generated by Django 4.2.1 on 2023-05-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
            ],
            options={
                'verbose_name': 'Рабочие смены',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='prepay',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='master',
            name='workplace',
            field=models.ManyToManyField(blank=True, related_name='master', to='order_bot.salon', verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='salon',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='open_time',
            field=models.TimeField(null=True),
        ),
        migrations.RemoveField(
            model_name='master',
            name='service',
        ),
        migrations.AddField(
            model_name='master',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='masters', to='order_bot.procedure', verbose_name='Услуги мастера'),
        ),
    ]
