# Generated by Django 4.2.1 on 2023-05-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_bot', '0002_more_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='procedures',
            field=models.ManyToManyField(related_name='salon', to='order_bot.procedure', verbose_name='Оказываемые услуги'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='close_time',
            field=models.TimeField(null=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='open_time',
            field=models.TimeField(null=True, verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='begin',
            field=models.TimeField(verbose_name='Начало смены'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='end',
            field=models.TimeField(verbose_name='Конец смены'),
        ),
    ]
