# Generated by Django 4.2.1 on 2023-05-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_bot', '0003_more_fields_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='workers',
            field=models.ManyToManyField(related_name='salon', to='order_bot.master', verbose_name='Наши специалисты'),
        ),
    ]
