# Generated by Django 4.2.1 on 2023-05-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_bot', '0004_add_masters_to_salon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktime',
            options={'verbose_name': 'Рабочие смены', 'verbose_name_plural': 'Рабочие смены'},
        ),
        migrations.AddField(
            model_name='master',
            name='worktime',
            field=models.ManyToManyField(blank=True, related_name='master', to='order_bot.worktime', verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='worktime',
            name='worker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime', to='order_bot.salon', verbose_name='Место работы'),
        ),
    ]
