# Generated by Django 4.2.1 on 2023-05-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_bot', '0005_add_worktime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='workplace',
        ),
    ]
