# Generated by Django 4.2.1 on 2023-05-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_bot', '0006_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Предоплата процедуры'),
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('worktime', models.ManyToManyField(related_name='worktime', to='order_bot.worktime', verbose_name='Рабочие смены дня')),
            ],
            options={
                'verbose_name_plural': 'Рабочие дни',
            },
        ),
        migrations.AddField(
            model_name='salon',
            name='days',
            field=models.ManyToManyField(related_name='salon', to='order_bot.workday', verbose_name='Рабочие дни'),
        ),
    ]
