# Generated by Django 4.2.1 on 2023-05-28 11:10

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('order_bot', '0007_add_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='master',
            name='worktime',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='days',
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, null=True, region=None, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='order_bot.procedure', verbose_name='Процедура'),
        ),
        migrations.AddField(
            model_name='worktime',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workplace', to='order_bot.salon', verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='day',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime', to='order_bot.master', verbose_name='Мастер'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
