# Generated by Django 4.2.1 on 2023-05-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_bot', '0008_client_to_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=20, verbose_name='Промокод')),
                ('status', models.BooleanField(null=True, verbose_name='Статус:')),
            ],
        ),
    ]
