# Generated by Django 4.2.1 on 2023-05-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_bot', '0009_promo_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='promo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Статус'),
        ),
    ]
